#!/bin/bash
# Set up directories first.
if [ -z "$XDG_CONFIG_HOME" ]; then 
	configdir="$HOME/.config"
else
	configdir="$XDG_CONFIG_HOME"
fi
statedir="`cat "$configdir"/kittylauncherrc | grep ^statedir \
| cut -d '=' -f 2-2`"
if [ -z "$statedir" ]; then
	if [ -z "$XDG_STATE_HOME" ]; then
		statedir="$HOME/.local/state/kittylauncher"
	else
		statedir="$XDG_STATE_HOME/kittylauncher"
	fi
fi
configdir="`eval echo "$configdir"`"
statedir="`eval echo "$statedir"`"

# Parse arguments of `kitty-launch` and save to _output.
if grep -qE "^$1;;|^;$1;" "$configdir"/kittylauncherrc; then
	app="`grep "$1" "$configdir"/kittylauncherrc | head -n1 \
	| cut -d ';' -f 3-3`"
	argnum="`grep "$1" "$configdir"/kittylauncherrc | head -n1 \
	| cut -d ';' -f 4-4`"
        if [ "$argnum" = "0" ]; then
        	fullapp="$app"	
        elif [ "$argnum" = "1" ]; then
                fullapp="$app $2"
        elif [ "$argnum" = "2" ]; then
                fullapp="$app $2 $3"
        else 
		fullapp="$app $*"
	fi
	echo "$fullapp" | tee "$statedir"/_output
else
	echo "true" | tee "$statedir"/_output
fi
